In [4]:
import pandas as pd

In [28]:
!ls

api/                         db.sqlite3                         uscities.csv*
cleaned_file_fuel_price.csv  fuel-prices-for-be-assessment.csv  venv/
config/                      manage.py*
data_processing.ipynb        requirements.txt

In [9]:
df = pd.read_csv("fuel-prices-for-be-assessment.csv", dtype=str)

In [26]:
# describe dataset
df.describe()

           rack_id  retail_price
count  8125.000000   8125.000000
mean    431.760123      3.498909
std     256.815966      0.418649
min      10.000000      2.687333
25%     240.000000      3.215667
50%     416.000000      3.432333
75%     618.000000      3.699000
max     982.000000      6.399000

In [10]:
# Standardize column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
)

In [11]:
df

,opis_truckstop_id,truckstop_name,address,city,state,rack_id,retail_price
0,7,WOODSHED OF BIG CABIN,"I-44, EXIT 283 & US-69",Big Cabin,OK,307,3.00733333
1,9,KWIK TRIP #796,"I-94, EXIT 143 & US-12 & SR-21",Tomah,WI,420,3.28733333
2,20,PILOT TRAVEL CENTER #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.899
3,20,PILOT #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.899
4,28,LITTLEFIELD EXPRESS #2,"I-540, EXIT 12 & US-71",Fort Smith,AR,645,3.399
...,...,...,...,...,...,...,...
8146,73127,Gas N Wash,"I-55, EXIT 285",Chicago,IL,290,3.399
8147,73128,ALLSUPS CONVENIENCE STORE #2477,HWY 69 & 11th st,Kiowa,OK,253,2.95733333
8148,73129,SHEETZ #837,I-94,Romulus,MI,325,3.099
8149,73130,A One Stop,"I-45, EXIT 246",Ennis,TX,630,2.93566666
8150,73131,Sheetz #838,"I-85, Exit 71",Salisbury,NC,46,2.859

In [12]:
# Strip whitespace from all string columns
df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)

In [13]:
# Title-case name & city; uppercase state

df["truckstop_name"] = df["truckstop_name"].str.title()
df["city"]           = df["city"].str.title()
df["state"]          = df["state"].str.upper()

In [14]:
df

,opis_truckstop_id,truckstop_name,address,city,state,rack_id,retail_price
0,7,Woodshed Of Big Cabin,"I-44, EXIT 283 & US-69",Big Cabin,OK,307,3.00733333
1,9,Kwik Trip #796,"I-94, EXIT 143 & US-12 & SR-21",Tomah,WI,420,3.28733333
2,20,Pilot Travel Center #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.899
3,20,Pilot #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.899
4,28,Littlefield Express #2,"I-540, EXIT 12 & US-71",Fort Smith,AR,645,3.399
...,...,...,...,...,...,...,...
8146,73127,Gas N Wash,"I-55, EXIT 285",Chicago,IL,290,3.399
8147,73128,Allsups Convenience Store #2477,HWY 69 & 11th st,Kiowa,OK,253,2.95733333
8148,73129,Sheetz #837,I-94,Romulus,MI,325,3.099
8149,73130,A One Stop,"I-45, EXIT 246",Ennis,TX,630,2.93566666
8150,73131,Sheetz #838,"I-85, Exit 71",Salisbury,NC,46,2.859

In [15]:
#  Convert numeric columns
df["rack_id"]       = pd.to_numeric(df["rack_id"], errors="coerce")
df["retail_price"]  = pd.to_numeric(df["retail_price"], errors="coerce")

In [16]:
df

,opis_truckstop_id,truckstop_name,address,city,state,rack_id,retail_price
0,7,Woodshed Of Big Cabin,"I-44, EXIT 283 & US-69",Big Cabin,OK,307,3.007333
1,9,Kwik Trip #796,"I-94, EXIT 143 & US-12 & SR-21",Tomah,WI,420,3.287333
2,20,Pilot Travel Center #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.899000
3,20,Pilot #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.899000
4,28,Littlefield Express #2,"I-540, EXIT 12 & US-71",Fort Smith,AR,645,3.399000
...,...,...,...,...,...,...,...
8146,73127,Gas N Wash,"I-55, EXIT 285",Chicago,IL,290,3.399000
8147,73128,Allsups Convenience Store #2477,HWY 69 & 11th st,Kiowa,OK,253,2.957333
8148,73129,Sheetz #837,I-94,Romulus,MI,325,3.099000
8149,73130,A One Stop,"I-45, EXIT 246",Ennis,TX,630,2.935667
8150,73131,Sheetz #838,"I-85, Exit 71",Salisbury,NC,46,2.859000

In [19]:
# Before dropping duplicates

print(f"length of the dataframe: {len(df)}")

length of the dataframe: 8151

In [20]:
#  Drop duplicate rows
df = df.drop_duplicates()

In [21]:
# After dropping duplicates

print(f"length of the dataframe: {len(df)}")

length of the dataframe: 8125

In [22]:
df

,opis_truckstop_id,truckstop_name,address,city,state,rack_id,retail_price
0,7,Woodshed Of Big Cabin,"I-44, EXIT 283 & US-69",Big Cabin,OK,307,3.007333
1,9,Kwik Trip #796,"I-94, EXIT 143 & US-12 & SR-21",Tomah,WI,420,3.287333
2,20,Pilot Travel Center #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.899000
3,20,Pilot #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.899000
4,28,Littlefield Express #2,"I-540, EXIT 12 & US-71",Fort Smith,AR,645,3.399000
...,...,...,...,...,...,...,...
8146,73127,Gas N Wash,"I-55, EXIT 285",Chicago,IL,290,3.399000
8147,73128,Allsups Convenience Store #2477,HWY 69 & 11th st,Kiowa,OK,253,2.957333
8148,73129,Sheetz #837,I-94,Romulus,MI,325,3.099000
8149,73130,A One Stop,"I-45, EXIT 246",Ennis,TX,630,2.935667
8150,73131,Sheetz #838,"I-85, Exit 71",Salisbury,NC,46,2.859000

In [23]:
# Reset index
df = df.reset_index(drop=True)

In [27]:
# Attaching longtitude and  latitude of 31k Cities - downloadable here https://simplemaps.com/data/us-cities

In [38]:
uscities_df = pd.read_csv("uscities.csv")[['city', 'state_id','lat','lng']].rename(columns={"state_id": "state"})

In [72]:
uscities_df = uscities_df.drop_duplicates(subset=["city", "state"], keep="first")

In [77]:
uscities_df = uscities_df.drop_duplicates(subset=["city", "state"], keep="first")

# save only langitude and latitude of cities as separate csv
uscities_df.to_csv("state_city_coordinates.csv", index=False)

In [73]:
df_merged = df.merge(
    uscities_df,
    on=["city", "state"],
    how="left"  # keeps all rows from df1, adds lat/lng where match found
)

print(df_merged.shape)
final_df = pd.DataFrame(df_merged)

(8125, 9)

In [74]:
final_df.reset_index(drop=True)

,opis_truckstop_id,truckstop_name,address,city,state,rack_id,retail_price,lat,lng
0,7,Woodshed Of Big Cabin,"I-44, EXIT 283 & US-69",Big Cabin,OK,307,3.007333,36.5423,-95.2220
1,9,Kwik Trip #796,"I-94, EXIT 143 & US-12 & SR-21",Tomah,WI,420,3.287333,43.9879,-90.4999
2,20,Pilot Travel Center #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.899000,32.9662,-112.7154
3,20,Pilot #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.899000,32.9662,-112.7154
4,28,Littlefield Express #2,"I-540, EXIT 12 & US-71",Fort Smith,AR,645,3.399000,35.3495,-94.3695
...,...,...,...,...,...,...,...,...,...
8120,73127,Gas N Wash,"I-55, EXIT 285",Chicago,IL,290,3.399000,41.8375,-87.6866
8121,73128,Allsups Convenience Store #2477,HWY 69 & 11th st,Kiowa,OK,253,2.957333,34.7230,-95.9025
8122,73129,Sheetz #837,I-94,Romulus,MI,325,3.099000,42.2237,-83.3660
8123,73130,A One Stop,"I-45, EXIT 246",Ennis,TX,630,2.935667,32.3254,-96.6347
8124,73131,Sheetz #838,"I-85, Exit 71",Salisbury,NC,46,2.859000,35.6658,-80.4905

In [76]:
final_df.to_csv("final_fuel_price_data.csv")